# Python Important Notes

1) What is the difference between tuple and list?  
When created one tuple variable, it can't be edited. But list can be changable everytime. Using tuple is more faster using list. How you should use tuple and list? 

In [1]:
list = [33, 'Turkey', 19]
tuple = (33, 'Turkey' , 19)

2) List and Array and Dictionary
The list is the core of python variable, but array is numpy framework variable. They are used to store variable. Array has a constant size. 

In [76]:
#Define Variable 
import random 
import numpy as np 
list_ex = [0, 1, 2, 3, 4]        #define list
array_ex = np.array([0,1,2,3,4]) #define array
dictionary_ex = {"merve":26}     #define dictionary

print(list_ex)
print(array_ex)
print(dictionary_ex)

[0, 1, 2, 3, 4]
[0 1 2 3 4]
{'merve': 26}


In [87]:
#Adding Value
list_ex.append(5)               #added data for list
array_ex = np.append(c,5)        #added data for numpy array
dictionary_ex.update({'turhan': 27}) #added data for dictionary
print(list_ex)
print(array_ex)
print(dictionary_ex)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]
{'merve': 26, 'turhan': 27}


In [88]:
#Deleting Value
list_ex.remove(5)            #variable delete
array_ex = np.delete(c,1)    #delete with spesific index 
dictionary_ex.pop('turhan')  #key value delete
print(list_ex)
print(array_ex)
print(dictionary_ex)

[0, 1, 2, 3, 4]
[0 2 3 4]
{'merve': 26}


3) Miracle Print Command and Important notes

In [12]:
#Don't skip the other row 
print("Merve",end = '')
print("Huseyin")

MerveHuseyin


In [46]:
#integer variable print
i = 3
k = 4.0
#print integer 
print ("First number %d and second number is %d" %(i, k))

First number 3 and second number is 4


3) Math operation
    * "and" ve "or" matematical operation
    

In [90]:
# Divide
print(6/5) # "/" give us double variable
print(6//5) # "// " give us integer variable

1.2
1


In [16]:
# Mod 
print(5%3)

2


In [92]:
#input prompt
k = int(input())   #integer input 
m = float(input()) #float input
j = input()        #string input 
print(k,type(k))
print(m,type(m))
print(j,type(j))

3
4
5
3 <class 'int'>
4.0 <class 'float'>
5 <class 'str'>


In [55]:
s = "merve"  #define string 
print(s[::2]) #print with two skip variable
print(s[1::2])#print start index = 1 with two skip variable

mre
ev


In [111]:
listA = [0]
listB = listA
listB.append(1)
print(listA)

[0, 1]
